parameters:
#    alfred_insight.example.class: Alfred\InsightBundle\Example

services:
#    alfred_insight.example:
#        class: %alfred_insight.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
